name: Upload to Pi
on:
  push:
    branches:
      - main
jobs:
  builds:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: SCP Files
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          port: ${{ secrets.SSH_PORT }}
          key: ${{ secrets.SSH_KEY }}
          passphrase: ${{ secrets.SSH_PASSPHRASE }}
          source: "./*"
          target: "/var/www/html/"
      - name: add symlink between the public folder and the apache one
        uses: garygrossgarten/github-action-ssh@release
        with:
          command: ln -sd ${{ secrets.PUBLIC_FOLDER_PATH }} /var/www/http/
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          port: ${{ secrets.SSH_PORT }}
          passphrase: ${{ secrets.SSH_PASSPHRASE }}
          privateKey: ${{ secrets.SSH_KEY}}
